In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv('covid_toy.csv')

In [4]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [5]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [7]:
X_train

    age  gender  fever   cough       city
36   38  Female  101.0    Mild  Bangalore
61   81  Female   98.0  Strong     Mumbai
7    20  Female    NaN  Strong     Mumbai
68   54  Female  104.0  Strong    Kolkata
63   10    Male  100.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
24   13  Female  100.0  Strong    Kolkata
30   15    Male  101.0    Mild      Delhi
46   19  Female  101.0    Mild     Mumbai
31   83    Male  103.0    Mild    Kolkata
23   80  Female   98.0    Mild      Delhi

[80 rows x 5 columns]

Aam Zindagi

In [8]:
# adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])

X_train_fever.shape

(80, 1)

In [9]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [10]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first',sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [11]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [12]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed.shape

(80, 7)

Mmentos Zindagi

In [13]:
from sklearn.compose import ColumnTransformer

In [14]:
transformer = ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(), ['fever']),
    ('tnf2', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough']),
    ('tnf3', OneHotEncoder(sparse_output=False, drop='first'), ['gender', 'city'])
], remainder='passthrough')

In [15]:
transformer.fit_transform(X_train)

array([[101.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,  38.   ],
       [ 98.   ,   1.   ,   0.   ,   0.   ,   0.   ,   1.   ,  81.   ],
       [100.875,   1.   ,   0.   ,   0.   ,   0.   ,   1.   ,  20.   ],
       [104.   ,   1.   ,   0.   ,   0.   ,   1.   ,   0.   ,  54.   ],
       [100.   ,   0.   ,   1.   ,   0.   ,   0.   ,   0.   ,  10.   ],
       [101.   ,   1.   ,   1.   ,   0.   ,   0.   ,   0.   ,  47.   ],
       [100.875,   0.   ,   1.   ,   1.   ,   0.   ,   0.   ,  38.   ],
       [100.875,   1.   ,   0.   ,   0.   ,   0.   ,   1.   ,  34.   ],
       [ 99.   ,   1.   ,   0.   ,   0.   ,   0.   ,   0.   ,  49.   ],
       [ 99.   ,   0.   ,   1.   ,   0.   ,   0.   ,   0.   ,  65.   ],
       [101.   ,   0.   ,   0.   ,   0.   ,   1.   ,   0.   ,  83.   ],
       [104.   ,   0.   ,   0.   ,   0.   ,   1.   ,   0.   ,   6.   ],
       [102.   ,   0.   ,   1.   ,   0.   ,   0.   ,   0.   ,  64.   ],
       [ 98.   ,   1.   ,   1.   ,   0.   ,   0.   ,   0.   ,  12.   ],
       [104.   ,   1.   ,   0.   ,   1.   ,   0.   ,   0.   ,  75.   ],
       [104.   ,   0.   ,   1.   ,   0.   ,   0.   ,   1.   ,  42.   ],
       [100.875,   0.   ,   1.   ,   0.   ,   1.   ,   0.   ,  82.   ],
       [102.   ,   0.   ,   0.   ,   1.   ,   0.   ,   0.   ,  49.   ],
       [100.   ,   0.   ,   0.   ,   0.   ,   1.   ,   0.   ,   5.   ],
       [100.   ,   0.   ,   1.   ,   0.   ,   0.   ,   0.   ,  11.   ],
       [ 98.   ,   0.   ,   1.   ,   0.   ,   1.   ,   0.   ,  24.   ],
       [100.875,   1.   ,   1.   ,   0.   ,   1.   ,   0.   ,  71.   ],
       [100.   ,   1.   ,   0.   ,   0.   ,   1.   ,   0.   ,  11.   ],
       [101.   ,   0.   ,   0.   ,   1.   ,   0.   ,   0.   ,  49.   ],
       [104.   ,   0.   ,   1.   ,   0.   ,   0.   ,   1.   ,  44.   ],
       [ 99.   ,   0.   ,   1.   ,   0.   ,   0.   ,   0.   ,  72.   ],
       [100.875,   1.   ,   0.   ,   0.   ,   0.   ,   0.   ,  42.   ],
       [ 98.   ,   1.   ,   0.   ,   1.   ,   0.   ,   0.   ,  40.   ],
       [103.   ,   0.   ,   0.   ,   0.   ,   1.   ,   0.   ,  48.   ],
       [ 99.   ,   0.   ,   0.   ,   0.   ,   0.   ,   1.   ,  14.   ],
       [100.   ,   0.   ,   1.   ,   0.   ,   1.   ,   0.   ,  27.   ],
       [ 99.   ,   0.   ,   1.   ,   1.   ,   0.   ,   0.   ,  65.   ],
       [ 99.   ,   1.   ,   0.   ,   0.   ,   1.   ,   0.   ,  25.   ],
       [101.   ,   0.   ,   1.   ,   1.   ,   0.   ,   0.   ,  19.   ],
       [101.   ,   1.   ,   1.   ,   0.   ,   0.   ,   0.   ,  14.   ],
       [101.   ,   0.   ,   0.   ,   1.   ,   0.   ,   0.   ,  64.   ],
       [104.   ,   0.   ,   1.   ,   0.   ,   1.   ,   0.   ,  16.   ],
       [100.   ,   0.   ,   1.   ,   0.   ,   1.   ,   0.   ,  55.   ],
       [100.875,   1.   ,   1.   ,   0.   ,   1.   ,   0.   ,  79.   ],
       [102.   ,   1.   ,   1.   ,   1.   ,   0.   ,   0.   ,  20.   ],
       [ 98.   ,   0.   ,   0.   ,   0.   ,   1.   ,   0.   ,  31.   ],
       [ 99.   ,   1.   ,   1.   ,   0.   ,   0.   ,   0.   ,  66.   ],
       [ 98.   ,   0.   ,   0.   ,   0.   ,   0.   ,   1.   ,  65.   ],
       [101.   ,   0.   ,   0.   ,   0.   ,   0.   ,   1.   ,  81.   ],
       [104.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,  18.   ],
       [102.   ,   0.   ,   1.   ,   0.   ,   0.   ,   1.   ,  74.   ],
       [104.   ,   0.   ,   1.   ,   0.   ,   0.   ,   0.   ,  51.   ],
       [103.   ,   0.   ,   1.   ,   0.   ,   1.   ,   0.   ,  60.   ],
       [103.   ,   0.   ,   0.   ,   1.   ,   0.   ,   0.   ,  73.   ],
       [ 98.   ,   0.   ,   1.   ,   1.   ,   0.   ,   0.   ,  83.   ],
       [102.   ,   0.   ,   1.   ,   0.   ,   1.   ,   0.   ,   5.   ],
       [100.   ,   0.   ,   0.   ,   0.   ,   1.   ,   0.   ,  19.   ],
       [100.   ,   0.   ,   1.   ,   0.   ,   0.   ,   0.   ,  80.   ],
       [101.   ,   1.   ,   0.   ,   0.   ,   1.   ,   0.   ,  51.   ],
       [ 98.   ,   1.   ,   0.   ,   0.   ,   1.   ,   0.   ,  10.   ],
       [102.   ,   1.   ,   0.   ,   0.   ,   1.   ,   0.   ,  82.   ],
       [ 98.   ,   1.   ,   0.   ,   0.   ,   1.   ,   0.   ,  71.   ],
       [102.   ,   1.   ,   0.   ,   1.   ,   0.   ,   0.   ,  33.   ],
       [100.875,   0.   ,   1.   ,   0.   ,   0.   ,   1.   ,  23.   ],
       [103.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,  16.   ],
       [100.   ,   0.   ,   1.   ,   1.   ,   0.   ,   0.   ,  27.   ],
       [ 98.   ,   1.   ,   0.   ,   0.   ,   0.   ,   1.   ,  69.   ],
       [100.   ,   1.   ,   0.   ,   0.   ,   0.   ,   0.   ,  19.   ],
       [104.   ,   0.   ,   1.   ,   0.   ,   0.   ,   0.   ,  25.   ],
       [ 99.   ,   1.   ,   0.   ,   1.   ,   0.   ,   0.   ,  59.   ],
       [104.   ,   1.   ,   0.   ,   1.   ,   0.   ,   0.   ,  34.   ],
       [ 98.   ,   1.   ,   1.   ,   0.   ,   1.   ,   0.   ,  34.   ],
       [104.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,  12.   ],
       [101.   ,   1.   ,   0.   ,   1.   ,   0.   ,   0.   ,  34.   ],
       [103.   ,   1.   ,   1.   ,   0.   ,   1.   ,   0.   ,  70.   ],
       [104.   ,   0.   ,   0.   ,   0.   ,   1.   ,   0.   ,  17.   ],
       [101.   ,   0.   ,   1.   ,   1.   ,   0.   ,   0.   ,  42.   ],
       [100.   ,   0.   ,   1.   ,   1.   ,   0.   ,   0.   ,  27.   ],
       [104.   ,   1.   ,   0.   ,   0.   ,   0.   ,   0.   ,  56.   ],
       [ 98.   ,   0.   ,   0.   ,   0.   ,   1.   ,   0.   ,  26.   ],
       [100.   ,   1.   ,   0.   ,   0.   ,   1.   ,   0.   ,  13.   ],
       [101.   ,   0.   ,   1.   ,   1.   ,   0.   ,   0.   ,  15.   ],
       [101.   ,   0.   ,   0.   ,   0.   ,   0.   ,   1.   ,  19.   ],
       [103.   ,   0.   ,   1.   ,   0.   ,   1.   ,   0.   ,  83.   ],
       [ 98.   ,   0.   ,   0.   ,   1.   ,   0.   ,   0.   ,  80.   ]])

In [16]:
transformer.fit_transform(X_train).shape

(80, 7)

In [17]:
transformer.transform(X_test)

array([[102.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,  69.   ],
       [102.   ,   1.   ,   0.   ,   0.   ,   0.   ,   0.   ,  24.   ],
       [101.   ,   1.   ,   0.   ,   1.   ,   0.   ,   0.   ,  68.   ],
       [101.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,  20.   ],
       [100.   ,   1.   ,   0.   ,   0.   ,   0.   ,   0.   ,  47.   ],
       [ 99.   ,   0.   ,   0.   ,   0.   ,   0.   ,   1.   ,  60.   ],
       [100.875,   0.   ,   0.   ,   1.   ,   0.   ,   0.   ,  75.   ],
       [ 98.   ,   1.   ,   1.   ,   0.   ,   0.   ,   1.   ,  23.   ],
       [101.   ,   0.   ,   0.   ,   0.   ,   0.   ,   1.   ,  65.   ],
       [103.   ,   0.   ,   0.   ,   0.   ,   1.   ,   0.   ,  50.   ],
       [104.   ,   0.   ,   1.   ,   0.   ,   1.   ,   0.   ,  51.   ],
       [100.875,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,  84.   ],
       [ 98.   ,   0.   ,   1.   ,   0.   ,   0.   ,   0.   ,  73.   ],
       [ 98.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,  64.   ],
       [103.   ,   0.   ,   0.   ,   0.   ,   1.   ,   0.   ,  69.   ],
       [ 98.   ,   1.   ,   0.   ,   0.   ,   0.   ,   1.   ,   5.   ],
       [103.   ,   1.   ,   1.   ,   0.   ,   0.   ,   0.   ,  46.   ],
       [102.   ,   1.   ,   0.   ,   0.   ,   0.   ,   0.   ,  82.   ],
       [101.   ,   0.   ,   0.   ,   0.   ,   1.   ,   0.   ,   8.   ],
       [ 99.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,  22.   ]])

In [18]:
transformer.transform(X_test).shape

(20, 7)